/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import java.awt.Dialog;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.Dictionary;
import java.util.List;
import java.util.Random;

/**
 *
 * @author Miguel
 */
public class Principal extends javax.swing.JFrame {

    String modojogo = "";
    String[][] matriz = new String[3][3];
    String vezjogador = "";
    int contadorjogada = 0;
    int jogadasLivres = 0;
    String jogador = "";
    int pontuacao = 0;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Principal.class.getName());

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jb2 = new javax.swing.JButton();
        jBnovo = new javax.swing.JButton();
        jb3 = new javax.swing.JButton();
        jb9 = new javax.swing.JButton();
        jb1 = new javax.swing.JButton();
        jb4 = new javax.swing.JButton();
        jb5 = new javax.swing.JButton();
        jb6 = new javax.swing.JButton();
        jb7 = new javax.swing.JButton();
        jb8 = new javax.swing.JButton();
        JCBPVP = new javax.swing.JCheckBox();
        JCBIAfacil = new javax.swing.JCheckBox();
        JCBIADificil = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb2.setEnabled(false);
        jb2.addActionListener(this::jb2ActionPerformed);
        getContentPane().add(jb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 80, 50));

        jBnovo.setText("Novo Jogo");
        jBnovo.addActionListener(this::jBnovoActionPerformed);
        getContentPane().add(jBnovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, 36));

        jb3.setEnabled(false);
        jb3.addActionListener(this::jb3ActionPerformed);
        getContentPane().add(jb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 80, 50));

        jb9.setEnabled(false);
        jb9.addActionListener(this::jb9ActionPerformed);
        getContentPane().add(jb9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 80, 50));

        jb1.setEnabled(false);
        jb1.addActionListener(this::jb1ActionPerformed);
        getContentPane().add(jb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 80, 50));

        jb4.setEnabled(false);
        jb4.addActionListener(this::jb4ActionPerformed);
        getContentPane().add(jb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 80, 50));

        jb5.setEnabled(false);
        jb5.addActionListener(this::jb5ActionPerformed);
        getContentPane().add(jb5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 80, 50));

        jb6.setEnabled(false);
        jb6.addActionListener(this::jb6ActionPerformed);
        getContentPane().add(jb6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 80, 50));

        jb7.setEnabled(false);
        jb7.addActionListener(this::jb7ActionPerformed);
        getContentPane().add(jb7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 80, 50));

        jb8.setEnabled(false);
        jb8.addActionListener(this::jb8ActionPerformed);
        getContentPane().add(jb8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 80, 50));

        buttonGroup1.add(JCBPVP);
        JCBPVP.setText("PVP");
        getContentPane().add(JCBPVP, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        buttonGroup1.add(JCBIAfacil);
        JCBIAfacil.setText("IA Fácil");
        getContentPane().add(JCBIAfacil, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        buttonGroup1.add(JCBIADificil);
        JCBIADificil.setText("IA Difícil");
        getContentPane().add(JCBIADificil, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));

        setSize(new java.awt.Dimension(382, 394));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnovoActionPerformed
        verificaModo();

        if (modojogo != "") {
            habilitabotoes(true);
            habilitaCheckBox(false);
            limpaBotoes();
            preencheMatriz(matriz);
            jBnovo.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um modo para jogar");
        }

    }//GEN-LAST:event_jBnovoActionPerformed

    private void jb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb1ActionPerformed

        jogaBotao(jb1);

    }//GEN-LAST:event_jb1ActionPerformed

    private void jb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb2ActionPerformed
        jogaBotao(jb2);
    }//GEN-LAST:event_jb2ActionPerformed

    private void jb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb3ActionPerformed
        jogaBotao(jb3);

    }//GEN-LAST:event_jb3ActionPerformed

    private void jb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb4ActionPerformed
        jogaBotao(jb4);

    }//GEN-LAST:event_jb4ActionPerformed

    private void jb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb5ActionPerformed
        jogaBotao(jb5);
    }//GEN-LAST:event_jb5ActionPerformed

    private void jb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb6ActionPerformed
        jogaBotao(jb6);
    }//GEN-LAST:event_jb6ActionPerformed

    private void jb7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb7ActionPerformed
        jogaBotao(jb7);
    }//GEN-LAST:event_jb7ActionPerformed

    private void jb8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb8ActionPerformed
        jogaBotao(jb8);
    }//GEN-LAST:event_jb8ActionPerformed

    private void jb9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb9ActionPerformed
        jogaBotao(jb9);
    }//GEN-LAST:event_jb9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Principal().setVisible(true));
    }

    public void habilitabotoes(boolean valor) {
        jb1.setEnabled(valor);
        jb2.setEnabled(valor);
        jb3.setEnabled(valor);
        jb4.setEnabled(valor);
        jb5.setEnabled(valor);
        jb6.setEnabled(valor);
        jb7.setEnabled(valor);
        jb8.setEnabled(valor);
        jb9.setEnabled(valor);
    }

    public void verificaModo() {
        if (JCBPVP.isSelected()) {
            modojogo = "pvp";
        } else if (JCBIAfacil.isSelected()) {
            modojogo = "ia_facil";
        } else if (JCBIADificil.isSelected()) {
            modojogo = "ia_dificil";
        }
    }

    public void resetaJogo() {
        contadorjogada = 0;
        limpaBotoes();
        habilitabotoes(false);
        preencheMatriz(matriz);
        jBnovo.setEnabled(true);
        habilitaCheckBox(true);
        verificaModo();
    }

    public void habilitaCheckBox(boolean valor) {
        JCBPVP.setEnabled(valor);
        JCBIAfacil.setEnabled(valor);
        JCBIADificil.setEnabled(valor);
    }

    public void jogaBotao(javax.swing.JButton botao) {
        String resultado;

        /*String jogador1 = "X";
        String jogador2 = "O";*/
        if (!botao.getText().equals("")) {
            return;
        }

        if (modojogo == "pvp") {

            realizaJogada(botao, matriz, modojogo);

            resultado = verificaGanhador(matriz, vezjogador);

            trataFimJogo(resultado, modojogo, vezjogador);

            return;
        }

        String vezIA = "O";

        if (modojogo == "ia_facil") {
            vezjogador = "X";

            realizaJogada(botao, matriz, modojogo);

            resultado = verificaGanhador(matriz, vezjogador);

            trataFimJogo(resultado, modojogo, vezjogador);

            jogadaIAFacil(matriz, contadorjogada);

            resultado = verificaGanhador(matriz, vezjogador);

            trataFimJogo(resultado, modojogo, vezjogador);

        }

        if (modojogo == "ia_dificil") {

            realizaJogada(botao, matriz, modojogo);

            resultado = verificaGanhador(matriz, vezjogador);

            trataFimJogo(resultado, modojogo, vezjogador);

            marcaPosicao(matriz, vezIA);

            resultado = verificaGanhador(matriz, vezIA);

            trataFimJogo(resultado, modojogo, vezjogador);

        }

    }

    public void realizaJogada(javax.swing.JButton botao, String[][] matriz, String modojogo) {
        String vezjogador = "";

        if (modojogo.equals("pvp")) {
            if (contadorjogada % 2 == 0) {
                vezjogador = "X";
            }

            if (contadorjogada % 2 != 0) {
                vezjogador = "O";
            }
        }

        if (modojogo.contains("ia")) {
            vezjogador = "X";
        }

        botao.setText(vezjogador);
        preencheMatriz(matriz);

        contadorjogada++;
    }

    public void trataFimJogo(String resultado, String modojogo, String vezjogador) {

        if (resultado.equals("")) {
            return;
        }

        if (resultado.equals("empate")) {
            JOptionPane.showMessageDialog(null, "Velha, jogo encerrado");
        }

        if (resultado.equals("O")) {
            if (modojogo.equals("ia_facil")) {
                JOptionPane.showMessageDialog(null, "IA Facil - " + resultado + " ganhou");
            }

            if (modojogo.equals("ia_dificil")) {
                JOptionPane.showMessageDialog(null, "IA Dificil - " + resultado + " ganhou");
            }

            if (modojogo.equals("pvp")) {
                JOptionPane.showMessageDialog(null, "Jogador - " + resultado + " ganhou");
            }
        }

        if (resultado.equals("X")) {
            JOptionPane.showMessageDialog(null, "Jogador - " + resultado + " ganhou");
        }

        resetaJogo();
    }

    public void jogadaIAFacil(String[][] matriz, int contadorjogada) {

        String vezIA = "O";

        Random numeroaleatorio = new Random();
        List<Posicao> jogadasPossiveis = new ArrayList<>();

        for (int linha = 0; linha < 3; linha++) {
            for (int coluna = 0; coluna < 3; coluna++) {
                if (matriz[linha][coluna].equals("")) {
                    jogadasPossiveis.add(new Posicao(linha, coluna));
                }
            }
        }

        int indice = numeroaleatorio.nextInt(jogadasPossiveis.size());

        Posicao jogada = jogadasPossiveis.get(indice);

        matriz[jogada.getLinha()][jogada.getColuna()] = vezIA;

        preencheBotoes(matriz);
        preencheMatriz(matriz);

    }

    /*
    public List<Object> jogadasPossiveis() {;

    List<Object> jogadasPossiveis = new ArrayList<Object>();

    for (int linha = 0; linha < 2; linha++) {
        for (int coluna = 0; coluna < 2; coluna++) {
            if (matriz[linha][coluna].equals("")) {
                jogadasPossiveis.add(new Posicao(linha, coluna));
            }
        }
    }
    return jogadasPossiveis;
}
     */

 /*
    public void jogadaIADificil() {

    //posicao da jogada do usuario
    List<Posicao> jogadasAdversario = new ArrayList<>();

    for (int linha = 0; linha < 3; linha++) {
        for (int coluna = 0; coluna < 3; coluna++) {
            if (matriz[linha][coluna] == vezjogador) {
                jogadasAdversario.add(new Posicao(linha, coluna));
            }
        }
    }

    //verifica onde o jogador esta tentando formar um trio 
    for (Posicao posicao : jogadasAdversario) {
        System.out.println(posicao.getLinha() + " " + posicao.getColuna());
    }

}*/
    public void marcaPosicao(String[][] matriz, String vezIA) {
        int[] posicao = new int[2];
        int pontuacao;
        int melhorPontuacao = Integer.MIN_VALUE;

        for (int linha = 0; linha < 3; linha++) {
            for (int coluna = 0; coluna < 3; coluna++) {
                if (matriz[linha][coluna].equals("")) {

                    matriz[linha][coluna] = vezIA;
                    pontuacao = miniMax(matriz, false);
                    matriz[linha][coluna] = "";

                    if (pontuacao > melhorPontuacao) {
                        melhorPontuacao = pontuacao;
                        posicao[0] = linha;
                        posicao[1] = coluna;

                    }
                }
            }
        }
        matriz[posicao[0]][posicao[1]] = vezIA;
        preencheBotoes(matriz);
    }

    public int miniMax(String[][] matriz, boolean vezMax) {
        int pontuacao;
        String resultado;
        String vezIA = "O";
        String vezjogador = "X";

        resultado = (vezMax) ? verificaGanhador(matriz, "X") : verificaGanhador(matriz, "O");

        if (resultado.equals("O")) {
            pontuacao = 1;
            return pontuacao;
        }

        if (resultado.equals("X")) {
            pontuacao = -1;
            return pontuacao;
        }

        if (resultado.equals("empate")) {
            pontuacao = 0;
            return pontuacao;
        }

        if (vezMax) {
            int melhorPontuacaoLocal = Integer.MIN_VALUE;
            /* funcao marca posica */
            for (int linha = 0; linha < 3; linha++) {
                for (int coluna = 0; coluna < 3; coluna++) {
                    if (matriz[linha][coluna].equals("")) {

                        matriz[linha][coluna] = vezIA;
                        pontuacao = miniMax(matriz, false);
                        matriz[linha][coluna] = "";

                        melhorPontuacaoLocal = max(pontuacao, melhorPontuacaoLocal);
                    }
                }
            }
            return melhorPontuacaoLocal;
        } else {
            int melhorPontuacaoLocal = Integer.MAX_VALUE;

            for (int linha = 0; linha < 3; linha++) {
                for (int coluna = 0; coluna < 3; coluna++) {
                    if (matriz[linha][coluna].equals("")) {

                        matriz[linha][coluna] = vezjogador;
                        pontuacao = miniMax(matriz, true);
                        matriz[linha][coluna] = "";

                        melhorPontuacaoLocal = min(pontuacao, melhorPontuacaoLocal);
                    }
                }
            }
            return melhorPontuacaoLocal;
        }

    }

    public int max(int pontuacao, int melhorPontuacao) {

        if (pontuacao > melhorPontuacao) {
            melhorPontuacao = pontuacao;
        }
        return melhorPontuacao;
    }

    public int min(int pontuacao, int melhorPontuacao) {

        if (pontuacao < melhorPontuacao) {
            melhorPontuacao = pontuacao;
        }
        return melhorPontuacao;
    }

    public void preencheMatriz(String[][] matriz) {
        matriz[0][0] = jb1.getText();
        matriz[0][1] = jb2.getText();
        matriz[0][2] = jb3.getText();
        matriz[1][0] = jb4.getText();
        matriz[1][1] = jb5.getText();
        matriz[1][2] = jb6.getText();
        matriz[2][0] = jb7.getText();
        matriz[2][1] = jb8.getText();
        matriz[2][2] = jb9.getText();
    }

    public void preencheBotoes(String[][] matriz) {
        jb1.setText(matriz[0][0]);
        jb2.setText(matriz[0][1]);
        jb3.setText(matriz[0][2]);
        jb4.setText(matriz[1][0]);
        jb5.setText(matriz[1][1]);
        jb6.setText(matriz[1][2]);
        jb7.setText(matriz[2][0]);
        jb8.setText(matriz[2][1]);
        jb9.setText(matriz[2][2]);
    }

    public void limpaBotoes() {
        jb1.setText("");
        jb2.setText("");
        jb3.setText("");
        jb4.setText("");
        jb5.setText("");
        jb6.setText("");
        jb7.setText("");
        jb8.setText("");
        jb9.setText("");
    }

    public String verificaGanhador(String[][] matriz, String jogador) {

        for (int i = 0; i < 3; i++) {
            if (matriz[i][0] != "" && matriz[i][0].equals(matriz[i][1]) && matriz[i][1].equals(matriz[i][2])) {

                return jogador;
            }

            if (matriz[0][i] != "" && matriz[0][i].equals(matriz[1][i]) && matriz[1][i].equals(matriz[2][i])) {
                return jogador;
            }

        }

        if (matriz[0][0] != "" && matriz[0][0].equals(matriz[1][1]) && matriz[1][1].equals(matriz[2][2])) {
            return jogador;
        }

        if (matriz[0][2] != "" && matriz[0][2].equals(matriz[1][1]) && matriz[1][1].equals(matriz[2][0])) {
            return jogador;
        }

        for (int linha = 0; linha < 3; linha++) {
            for (int coluna = 0; coluna < 3; coluna++) {

                if (matriz[linha][coluna] == "") {
                    return "";
                }
            }
        }

        return "empate";
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox JCBIADificil;
    private javax.swing.JCheckBox JCBIAfacil;
    private javax.swing.JCheckBox JCBPVP;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBnovo;
    private javax.swing.JButton jb1;
    private javax.swing.JButton jb2;
    private javax.swing.JButton jb3;
    private javax.swing.JButton jb4;
    private javax.swing.JButton jb5;
    private javax.swing.JButton jb6;
    private javax.swing.JButton jb7;
    private javax.swing.JButton jb8;
    private javax.swing.JButton jb9;
    // End of variables declaration//GEN-END:variables
}
